# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Bump version
      id: bump-version
      run: echo "::set-output name=version::$(npm version patch | cut -c 2-)"
    - run: npm i @vue/cli concurrently wait-on cross-env -g
    - run: npm i
    - run: npm run build --if-present
    - run: npm run build-win --if-present
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.bump-version.outputs.version }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: true
    - name: Upload Release Asset
      id: upload-release-dmg
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/*.dmg
        asset_name: chaat-${{ steps.bump-version.outputs.version }}.dmg
        asset_content_type: application/zip 
    - name: Upload Release Asset
      id: upload-release-exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/*.exe
        asset_name: chaat-${{ steps.bump-version.outputs.version }}-setup.exe
        asset_content_type: application/zip 
      
